// Mocks generated by Mockito 5.4.6 from annotations
// in weather/test/repositories/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:weather/core/result.dart' as _i8;
import 'package:weather/datasources/local/weather_local_datasource.dart'
    as _i10;
import 'package:weather/datasources/remote/weather_remote_datasource.dart'
    as _i6;
import 'package:weather/models/forecast.dart' as _i5;
import 'package:weather/models/location.dart' as _i3;
import 'package:weather/models/weather.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCityLocation_2 extends _i1.SmartFake implements _i3.CityLocation {
  _FakeCityLocation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCityWeather_3 extends _i1.SmartFake implements _i4.CityWeather {
  _FakeCityWeather_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCityForecast_4 extends _i1.SmartFake implements _i5.CityForecast {
  _FakeCityForecast_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasource extends _i1.Mock
    implements _i6.WeatherRemoteDatasource {
  MockWeatherRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Result<_i3.CityLocation>> getLocation(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#getLocation, [cityName]),
            returnValue: _i7.Future<_i8.Result<_i3.CityLocation>>.value(
              _i9.dummyValue<_i8.Result<_i3.CityLocation>>(
                this,
                Invocation.method(#getLocation, [cityName]),
              ),
            ),
          )
          as _i7.Future<_i8.Result<_i3.CityLocation>>);

  @override
  _i7.Future<_i8.Result<_i4.CityWeather>> getWeather(
    _i3.CityLocation? location,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeather, [location]),
            returnValue: _i7.Future<_i8.Result<_i4.CityWeather>>.value(
              _i9.dummyValue<_i8.Result<_i4.CityWeather>>(
                this,
                Invocation.method(#getWeather, [location]),
              ),
            ),
          )
          as _i7.Future<_i8.Result<_i4.CityWeather>>);

  @override
  _i7.Future<_i8.Result<_i5.CityForecast>> getForecast(
    String? cityName,
    int? days,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getForecast, [cityName, days]),
            returnValue: _i7.Future<_i8.Result<_i5.CityForecast>>.value(
              _i9.dummyValue<_i8.Result<_i5.CityForecast>>(
                this,
                Invocation.method(#getForecast, [cityName, days]),
              ),
            ),
          )
          as _i7.Future<_i8.Result<_i5.CityForecast>>);
}

/// A class which mocks [WeatherLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDatasource extends _i1.Mock
    implements _i10.WeatherLocalDatasource {
  MockWeatherLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.File configPathToFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#configPathToFile, [path]),
            returnValue: _FakeFile_0(
              this,
              Invocation.method(#configPathToFile, [path]),
            ),
          )
          as _i2.File);

  @override
  _i7.Future<_i2.File> createStore(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createStore, [path]),
            returnValue: _i7.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#createStore, [path])),
            ),
          )
          as _i7.Future<_i2.File>);

  @override
  _i7.Future<_i2.File> createCurrentStore(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#createCurrentStore, [cityName]),
            returnValue: _i7.Future<_i2.File>.value(
              _FakeFile_0(
                this,
                Invocation.method(#createCurrentStore, [cityName]),
              ),
            ),
          )
          as _i7.Future<_i2.File>);

  @override
  _i7.Future<void> findAndUpdateCurrentFile(
    _i3.CityLocation? location,
    _i4.CityWeather? weather,
    DateTime? lastCacheUpdated,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findAndUpdateCurrentFile, [
              location,
              weather,
              lastCacheUpdated,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  String getHistoryCachePath() =>
      (super.noSuchMethod(
            Invocation.method(#getHistoryCachePath, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getHistoryCachePath, []),
            ),
          )
          as String);

  @override
  String getCurrentCachePath(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentCachePath, [cityName]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getCurrentCachePath, [cityName]),
            ),
          )
          as String);

  @override
  _i7.Future<
    ({
      DateTime lastCacheUpdated,
      _i3.CityLocation location,
      _i4.CityWeather weather,
    })
  >
  loadCurrentWeatherFile(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentWeatherFile, [cityName]),
            returnValue:
                _i7.Future<
                  ({
                    DateTime lastCacheUpdated,
                    _i3.CityLocation location,
                    _i4.CityWeather weather,
                  })
                >.value((
                  lastCacheUpdated: _FakeDateTime_1(
                    this,
                    Invocation.method(#loadCurrentWeatherFile, [cityName]),
                  ),
                  location: _FakeCityLocation_2(
                    this,
                    Invocation.method(#loadCurrentWeatherFile, [cityName]),
                  ),
                  weather: _FakeCityWeather_3(
                    this,
                    Invocation.method(#loadCurrentWeatherFile, [cityName]),
                  ),
                )),
          )
          as _i7.Future<
            ({
              DateTime lastCacheUpdated,
              _i3.CityLocation location,
              _i4.CityWeather weather,
            })
          >);

  @override
  _i7.Future<List<({DateTime fetchedAt, int id, String name})>>
  loadHistoryFile() =>
      (super.noSuchMethod(
            Invocation.method(#loadHistoryFile, []),
            returnValue:
                _i7.Future<
                  List<({DateTime fetchedAt, int id, String name})>
                >.value(<({DateTime fetchedAt, int id, String name})>[]),
          )
          as _i7.Future<List<({DateTime fetchedAt, int id, String name})>>);

  @override
  _i7.Future<void> findAndUpdateHistoryByLocation(
    _i3.CityLocation? location,
    DateTime? lastCacheUpdated,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findAndUpdateHistoryByLocation, [
              location,
              lastCacheUpdated,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> deleteCache() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCache, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<
    ({
      _i5.CityForecast forecast,
      DateTime lastCacheUpdated,
      _i3.CityLocation location,
    })
  >
  loadForecastFile(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#loadForecastFile, [cityName]),
            returnValue:
                _i7.Future<
                  ({
                    _i5.CityForecast forecast,
                    DateTime lastCacheUpdated,
                    _i3.CityLocation location,
                  })
                >.value((
                  forecast: _FakeCityForecast_4(
                    this,
                    Invocation.method(#loadForecastFile, [cityName]),
                  ),
                  lastCacheUpdated: _FakeDateTime_1(
                    this,
                    Invocation.method(#loadForecastFile, [cityName]),
                  ),
                  location: _FakeCityLocation_2(
                    this,
                    Invocation.method(#loadForecastFile, [cityName]),
                  ),
                )),
          )
          as _i7.Future<
            ({
              _i5.CityForecast forecast,
              DateTime lastCacheUpdated,
              _i3.CityLocation location,
            })
          >);

  @override
  String getForecastCachePath(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastCachePath, [cityName]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getForecastCachePath, [cityName]),
            ),
          )
          as String);

  @override
  _i7.Future<void> findAndUpdateForecastByLocation(
    _i3.CityLocation? location,
    _i5.CityForecast? forecast,
    DateTime? lastCacheUpdated,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findAndUpdateForecastByLocation, [
              location,
              forecast,
              lastCacheUpdated,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.File> createForecastStore(String? cityName) =>
      (super.noSuchMethod(
            Invocation.method(#createForecastStore, [cityName]),
            returnValue: _i7.Future<_i2.File>.value(
              _FakeFile_0(
                this,
                Invocation.method(#createForecastStore, [cityName]),
              ),
            ),
          )
          as _i7.Future<_i2.File>);
}
